{#
    This template is used to generate SPARQL SELECT queries.
    This template takes 1 parameter:
     - context: the context from which the data is to be selected
#}

SELECT ?graph ?lastmod WHERE {
    GRAPH <{{ context }}> { ?graph <https://schema.org/dateModified> ?lastmod }
}