{#- Jinja Template for Sparql Query
 | Lists schema:Project instances with their (optional) schema:name
 | variables in template:
 |    - (optional) N: number of results you want (defaults to no limits --> full listing)
 |    - (optional) O: offset to apply when paging
 -#}
PREFIX schema: <http://schema.org/>
PREFIX lw: <http://lifewatch.org/ns/>

SELECT 
  (?s as ?user) 
  ?affiliation
  ?country
  ?group
  ?qh
WHERE { 
	?s a schema:Person .
    OPTIONAL {
        ?s schema:affiliation ?affil .
        ?affil schema:name ?affiliation .
        
        ?affil schema:address ?o .
        ?o schema:addressCountry ?country .

        ?affil lw:group ?group .
        ?affil lw:qh ?qh .
    }
}