version: "3.7"
# -----------------------------------------------------------------------
services: 
  jupyter:
    build:
      context: ./jupyter
    image: lwua/lwua_jupyter
    container_name: lwua_jupyter
    ports:
      - "8888:8888"
    links:
      - graphdb
    volumes:
      - "./notebooks:/notebooks"
    labels:
      be.vliz.container.project: "LWUA"
      be.vliz.container.group: "services"

  graphdb:
    # todo consider a local build that also initializes a repository for lwua inside this lwua_graphdb!
    image: ontotext/graphdb:10.0.2
    container_name: lwua_graphdb
    ports:
      - 7200:7200     # HTTP
    # todo - think about volumes for persistence of data
    labels:
      be.vliz.container.project: "LWUA"
      be.vliz.container.group: "services"

  ingest:
    build: 
      context: ./lwua-ingest/ 
      #args: 
    image: lwua/lwua_ingest
    container_name: lwua_ingest
    volumes: 
      - ../data:/data    # Store for any input data 
    env_file:
      - ../.env
    # for test / dev -- no restart and single run
    restart: "no"
    command: run
    # towards deploy -- make restart and keep service running -- consequence: use ctrl-c to stop
    # restart: unless-stopped 
    # command: start
    links:
      - graphdb
    logging:
      driver: json-file
      options:
        max-size: 10m 
    labels:
      be.vliz.container.project: "LWUA"
      be.vliz.container.group: "services"
      be.vliz.container.owner: "laurian.van.maledghem@vliz.be"
      be.vliz.container.description: "LifeWatch User-Analysis Platform"
      be.vliz.container.vcs-url: "https://github.com/lifewatch/user-analysis-2023.git"