snooze-till-graph-age-minutes: 0
prefix:
  rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
  dcat: <http://www.w3.org/ns/dcat#>
  schema: <https://schema.org/>
  org: <http://www.w3.org/ns/org#>
  dct: <http://purl.org/dc/terms/> 
  mi: <http://www.marineinfo.org/ns/ontology#>
assert:
  - subjects:
      literal:
        - http://dev.marineinfo.org/id/collection/919  # EurOBIS ackn
        - http://dev.marineinfo.org/id/collection/944  # EUROBIS ackn – direct,
        - http://dev.marineinfo.org/id/collection/945  # EUROBIS ackn – indirect
        - http://dev.marineinfo.org/id/collection/942  # IRMNG ackn
        - http://dev.marineinfo.org/id/collection/923  # Lifewatch ackn
        - http://dev.marineinfo.org/id/collection/986  # LifeWatch BopCo
        - http://dev.marineinfo.org/id/collection/897  # LifeWatch Marine Data Archeology
        - http://dev.marineinfo.org/id/collection/896  # LifeWatch Observatory
        - http://dev.marineinfo.org/id/collection/941  # LifeWatch Species Information Backbone
        - http://dev.marineinfo.org/id/collection/987  # LifeWatch Thematic Remote Sensing
        - http://dev.marineinfo.org/id/collection/793  # Marine Regions ackn
        - http://dev.marineinfo.org/id/collection/915  # WoRMS ackn
        - http://dev.marineinfo.org/id/collection/947  # WoRMS ackn - direct
    paths:
      - "<http://www.w3.org/ns/dcat#resource> "
  - subjects:
      SPARQL: >
        SELECT DISTINCT ?s
        WHERE {
              [] <http://www.w3.org/ns/dcat#resource> ?s .
              }
    paths:
      - "<https://schema.org/author>"
  - subjects:
      SPARQL: >
        PREFIX schema: <https://schema.org/>
        SELECT DISTINCT ?s
        WHERE {
          ?ok <https://schema.org/author> ?authorid .
          ?authorid <https://schema.org/identifier> ?s .
        }
    paths:
      - "<https://schema.org/affiliation>"
      - "<https://schema.org/givenName>"
      - "<https://schema.org/familyName>"
  - subjects:
      SPARQL: >
        SELECT DISTINCT ?affid
        WHERE {
            ?s <https://schema.org/affiliation> ?affid .
        }
    paths:
      - "<https://schema.org/name>"