subjects:
  literal: 
    - http://dev.marineinfo.org/id/collection/919  # EurOBIS ackn
    - http://dev.marineinfo.org/id/collection/944  # EUROBIS ackn – direct,
    - http://dev.marineinfo.org/id/collection/945  # EUROBIS ackn – indirect
    - http://dev.marineinfo.org/id/collection/942  # IRMNG ackn
    - http://dev.marineinfo.org/id/collection/923  # Lifewatch ackn
    - http://dev.marineinfo.org/id/collection/986  # LifeWatch BopCo
    - http://dev.marineinfo.org/id/collection/897  # LifeWatch Marine Data Archeology
    - http://dev.marineinfo.org/id/collection/896  # LifeWatch Observatory
    - http://dev.marineinfo.org/id/collection/941  # LifeWatch Species Information Backbone
    - http://dev.marineinfo.org/id/collection/987  # LifeWatch Thematic Remote Sensing
    - http://dev.marineinfo.org/id/collection/793  # Marine Regions ackn
    - http://dev.marineinfo.org/id/collection/915  # WoRMS ackn
    - http://dev.marineinfo.org/id/collection/947  # WoRMS ackn - direct
prefixes:
  dcat: <http://www.w3.org/ns/dcat#>
  schema: <https://schema.org/>
  org: <http://www.w3.org/ns/org#>
  dct: <http://purl.org/dc/terms/> 
assert-paths:
  # identifiers van alle resources (personen, instituten, projecten, events, publicaties en datasets) gelinkt aan een LW spcol 
  # (identifiers van personen moeten ervantussen wegens GDPR)
  # bij publicaties zijn dit: DOI, WoS code en VABB code
  - "dcat:resource / schema:identifier "

  # naam van affiliaties & projecten & events gelinkt aan een lifewatch special collection  
  - "dcat:resource / schema:name"

  # naam van affiliaties gelinkt aan een persoon in een lifewatch special collection
  # naam van het project / event gelinkt aan een LW spcol
  - "dcat:resource / org:hasMembership / org:organization / schema:name "
  
cache_lifetime: 180