subjects: 
  SPARQL: >
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX schema: <https://schema.org/>
    SELECT ?s
    WHERE {
      ?s rdf:type schema:Organization .
    }
assert-paths: 
cache_lifetime: 180