subjects: 
  SPARQL: >
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX dct: <http://purl.org/dc/terms/>
    SELECT ?s
    WHERE {
      ?s rdf:type dct:BibliographicResource .
    }
assert-paths: 
cache_lifetime: 180