{#- Jinja Template for Sparql Query
 | Lists schema:Project instances with their (optional) schema:name
 | variables in template:
 |    - (optional) N: number of results you want (defaults to no limits --> full listing)
 |    - (optional) O: offset to apply when paging
 -#}
PREFIX schema: <https://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/#>
PREFIX mi: <http://www.marineinfo.org/ns/ontology#>
         
SELECT 
  (?s as ?publication_url) 
  ?publ_type
  ?publish_date
  ?affil_name
  ?affil_id         
WHERE { 
	?s a dct:BibliographicResource .
    OPTIONAL {
        ?s dct:type ?publ_type .
        ?s schema:datePublished ?publish_date .
        }
    OPTIONAL {
        ?s schema:author ?Person .
        ?Person schema:familyName ?affil_name .
        ?Person schema:affiliation ?affil_id .
    }
}