subjects: 
  SPARQL: >
    PREFIX schema: <https://schema.org/>
    SELECT ?s ?p ?o
    WHERE {
      ?s ?p schema:Project .
    }
assert-paths: 
  - https://schema.org/Dataset
  - http://www.w3.org/1999/02/22-rdf-syntax-ns#type
cache_lifetime: 180