subjects: 
  SPARQL: >
    PREFIX schema: <https://schema.org/>
    SELECT ?s ?p ?o
    WHERE {
      ?s ?p schema:Dataset .
    }
assert-paths:
  - http://xmlns.com/foaf/0.1/Person
cache_lifetime: 180