subjects:
  literal: 
    - http://marineregions.org/mrgid/63523
    - http://marineregions.org/mrgid/2540
    - http://marineregions.org/mrgid/12548
prefixes:
  ex: <https://example.org/whatever/>
  mr: <http://marineregions.org/ns/ontology#>
assert-paths:
  - "mr:hasGeometry"
  #- "mr:isPartOf / mr:hasGeometry"
  - "mr:isPartOf / <https://schema.org/geo> / <https://schema.org/latitude>"
  - "mr:isPartOf/ <https://schema.org/geo>/<https://schema.org/longitude>"
  #- "mr:isPartOf/mr:hasGeometry    / <https://schema.org/latitude> /<https://schema.org/longitude>"
cache_lifetime: 180
