subjects:
  literal: 
    - http://marineregions.org/mrgid/63523
    - http://marineregions.org/mrgid/2540
    - http://marineregions.org/mrgid/12548
assert-paths:
  - http://marineregions.org/ns/ontology#hasGeometry
  - http://marineregions.org/ns/ontology#isPartOf:
    - http://marineregions.org/ns/ontology#hasGeometry
    - https://schema.org/geo:
      - https://schema.org/latitude
      - https://schema.org/longitude
cache_lifetime: 180
