PREFIX schema: <https://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/#>
               
SELECT DISTINCT
  ?publication 
  ?publish_date
  ?auth_affil_id
WHERE { 
	?publication a dct:BibliographicResource .
    OPTIONAL {
        ?publication schema:datePublished ?publish_date .
    }
    OPTIONAL {
        ?publication schema:author ?author .
        ?author schema:affiliation ?auth_affil_id .
    }
}