{#- Jinja Template for Sparql Query
# List affiliations of author(s) from all publications in LW spcol (LWspcol -> publications -> authors -> affiliation)
# Link to the standardized affiliations list
 -#}
PREFIX schema: <https://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX mi: <http://www.marineinfo.org/ns/ontology#>
PREFIX lw: <http://lifewatch.org/ns/>

SELECT DISTINCT
  (?publication_url as ?pub_id) 
  ?author_id             
WHERE { 
	?publication_url a dct:BibliographicResource .
    ?publication_url schema:author ?Author .
    OPTIONAL {
        ?Author schema:identifier ?author_id .
    }
}