{#- Jinja Template for Sparql Query
# 0.List affiliations of author(s) from all publications in LW spcol (LWspcol -> publications -> authors -> affiliation)
# 1.Link to the standardized affiliations list (for publications, this is via the marineinfo-url)  
# 2.Add country name & QH category info from the affiliation of (first) author(s) of a publication
 -#}
PREFIX schema: <https://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/#>
PREFIX mi: <http://www.marineinfo.org/ns/ontology#>
PREFIX lw: <http://lifewatch.org/ns/>

SELECT DISTINCT
  ?publication
  ?affiliation_id
  ?group
  ?quadruple_helix
               
WHERE { 
	?publication a dct:BibliographicResource .
    ?publication schema:author ?author .
    ?author schema:affiliation ?affiliation_id .
    ?affiliation_id lw:group ?group .
    ?affiliation_id lw:qh ?quadruple_helix.
}