{#- Jinja Template for Sparql Query
# List affiliations of author(s) from all publications in LW spcol (LWspcol -> publications -> authors -> affiliation)
# Link to the standardized affiliations list
 -#}
PREFIX schema: <https://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/#>
PREFIX mi: <http://www.marineinfo.org/ns/ontology#>
         
SELECT DISTINCT
  (?publication_url as ?publication)
  ?firstname
  ?lastname
WHERE { 
	?publication_url a dct:BibliographicResource . 
    ?publication_url schema:author ?Author .
    OPTIONAL {
        ?Author schema:givenName ?firstname .
        ?Author schema:familyName ?lastname .
    }
    OPTIONAL {
        ?Author schema:givenName ?firstname .
    } 
    OPTIONAL {
        ?Author schema:familyName ?lastname .
    } 
}

    {# authors can occur with both first & lastname, only lastname and only firstname --> hence use op 3optional statements #}