{#- Jinja Template for Sparql Query
# 0.List affiliations of author(s) from all publications in LW spcol (LWspcol -> publications -> authors -> affiliation)
# 1.Link to the standardized affiliations list (for publications, this is via the marineinfo-url)  
# 2.Add country name & QH category info from the affiliation of (first) author(s) of a publication
 -#}
PREFIX schema: <https://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX mi: <http://www.marineinfo.org/ns/ontology#>
PREFIX lw: <http://lifewatch.org/ns/>

SELECT DISTINCT
  (?publication_url as ?pub_id) 
  (?author_affiliation as ?affil_id)
  ?group
  ?qh
WHERE { 
	?publication_url a dct:BibliographicResource .
    ?publication_url schema:author ?Author .
    ?Author schema:affiliation ?author_affiliation .
    ?author_affiliation lw:group ?group .
    ?author_affiliation lw:qh ?qh .
}