PREFIX schema: <https://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/#>
PREFIX mi: <http://www.marineinfo.org/ns/ontology#>
         
SELECT DISTINCT
  ?publication 
  ?doctype
  ?litstyle
  ?publish_date     
  ?special_collection
WHERE { 
	?publication a dct:BibliographicResource .
    OPTIONAL {
        ?publication dct:type ?doctype .
    }
    OPTIONAL {
        ?publication mi:hasBibType ?litstyle .
    }
    OPTIONAL {
        ?publication schema:datePublished ?publish_date .
    }
    OPTIONAL {
        ?publication dct:isPartOf ?special_collection .
    }
}