PREFIX schema: <https://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/#>
PREFIX mi: <http://www.marineinfo.org/ns/ontology#>
         
SELECT 
  ?publication 
  ?publish_date
  ?title
  ?abstract
WHERE { 
	?publication a dct:BibliographicResource .
    OPTIONAL {
        ?publication schema:datePublished ?publish_date .
        }
    OPTIONAL {
        ?publication dct:title ?title .
    }
    OPTIONAL {
        ?publication dct:abstract ?abstract .
    }
}
